### ISSUE TITLE
Add turn rate and turn/slip indicator to PFD

### ISSUE THREAD

**Issue by Maker42** [makerplane/pyEfis#27]
Perhaps at the bottom of the AI, above the heading strip.

**Comment by neil-d95** [comment]
So I finally found something on the math for this. it was in FAA Instrument fly handbook H8083-15. 

The inclinometer does not indicate the amount of bank, neither
is it limited to an indication of slip; it only indicates the
relationship between the angle of bank and the rate of yaw

If found the found a few places the math for rate of turn vs angle of bank and airspeed.
http://www.flightlearnings.com/2009/08/26/rate-of-turn/

rate of turn = 1091*tan(angle of bank)/ True Airspeed.

Getting the rate of yaw from an IMU setup is the only thing I'm not sure on.

**Comment by birkelbach** [comment]
No that's not right.  You can skid all the way around a 360 degree turn and your yaw rate and turn rate will have to average out to the same over that time, or you'll end up flying backwards.  The only time they are different is for short periods of time when you are transitioning from skidding to slipping to coordinated.  This is actually a gross over simplification too because I can turn 180 degrees and never have a yaw rate > 0. It will give the slip/skid indicator fits though. :-)

When your yaw rate is lower than your turn rate your are **_transitioning_** more toward a slipping turn, and when your yaw rate is higher, more toward a skidding turn.  Once you are stabilized in that skid or slip your yaw rate and turn rate will again be equal but the ball in the skip/skid will still be deflected.  Because it reflects bank angle vs yaw rate.  Not turn rate vs yaw rate. You can't use that bank angle function to compare turn rate to yaw rate and then from that infer some slip or skid because the formula assumes a properly coordinated turn.

The Instrument Flying Handbook is not trying to explain to instrument designers how to design the instrument, it is trying to explain to fledgling instrument pilots how to interpret the meaning of the indication.  The slip/skid ball does **_indicate_** a relationship between bank angle and yaw rate, but that is not what it **_measures_**.  It measures the lateral acceleration.  Just like altimeters don't measure altitude and airspeed indicators don't measure speed.

**Comment by neil-d95** [comment]
Hey, let talk about this later this weekend if you have time. I must have missed type because I was talking about the difference in rate between angle of bank to rank vs yaw rate. it'll be deg/sec you can have a difference of negative.

  On January 31, 2019 at 8:49 AM Phil Birkelbach <notifications@github.com> wrote:
 
 
 No that's not right. You can skid all the way around a 360 degree turn and your yaw rate and turn rate will have to average out to the same over that time, or you'll end up flying backwards. The only time they are different is for short periods of time when you are transitioning from skidding to slipping to coordinated. This is actually a gross over simplification too because I can turn 180 degrees and never have a yaw rate > 0. It will give the slip/skid indicator fits though. :-) 
 When your yaw rate is lower than your turn rate your are transitioning more toward a slipping turn, and when your yaw rate is higher, more toward a skidding turn. Once you are stabilized in that skid or slip your yaw rate and turn rate will again be equal but the ball in the skip/skid will still be deflected. Because it reflects bank angle vs yaw rate. Not turn rate vs yaw rate. You can't use that bank angle function to compare turn rate to yaw rate and then from that infer some slip or skid because the formula assumes a properly coordinated turn. 
 The Instrument Flying Handbook is not trying to explain to instrument designers how to design the instrument, it is trying to explain to fledgling instrument pilots how to interpret the meaning of the indication. The slip/skid ball does indicate a relationship between bank angle and yaw rate, but that is not what it measures. It measures the lateral acceleration. Just like altimeters don't measure altitude and airspeed indicators don't measure speed.
